version: 2.1

commands:
  print_pipeline_id:
    description: "Print the Pipeline ID"
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  print_pip_ID:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id

workflows:
  my_work_flow:
    jobs:
      - print_pip_ID